export const CONTENT = {
  BACK: "بازگشت",
  PRODUCT_DESCRIPTION: "جزئیات محصول",
  CART: "سبد خرید",
  ADD_TO_CART: "افزودن به سبد خرید",
  PRODUCT_NOT_FOUND: "محصول یافت نشد",
  PRODUCT_NOT_FOUND_DESCRIPTION: "متأسفانه محصول مورد نظر یافت نشد",
  CART_EMPTY: "سبد خرید شما خالی است",
  CART_EMPTY_DESCRIPTION: "محصولات خود را به سبد خرید اضافه کنید",
  SUBTOTAL: "جمع:",
  TOTAL: "مجموع کل:",
  CHECKOUT: "پرداخت",
  CLEAR_CART: "پاک کردن",
  CLOSE: "بستن",
  DECREASE_QUANTITY: "کاهش تعداد",
  INCREASE_QUANTITY: "افزایش تعداد",
  VIEW: "مشاهده",
  NO_PRODUCTS_FOUND: "محصولی یافت نشد",
  NO_PRODUCTS_DESCRIPTION: "در حال حاضر محصولی در دسترس نیست",
  PRICE: "قیمت:",
  UNIT_PRICE: "قیمت واحد:",
  APP_TITLE: "اسنپ شاپ",
  APP_DESCRIPTION: "فروشگاه اینترنتی اسنپ شاپ",
  CART_ACTIONS: "عملیات سبد خرید",
  PAGE_NOT_FOUND: "صفحه یافت نشد",
  PAGE_NOT_FOUND_DESCRIPTION:
    "متأسفانه صفحه مورد نظر شما یافت نشد. ممکن است آدرس اشتباه باشد یا صفحه حذف شده باشد.",
  GO_HOME: "بازگشت به صفحه اصلی",
  ERROR_OCCURRED: "خطایی رخ داد",
  ERROR_DESCRIPTION:
    "متأسفانه خطایی در سیستم رخ داده است. لطفاً دوباره تلاش کنید.",
  TRY_AGAIN: "تلاش مجدد",
  ERROR_LOADING_PRODUCTS: "خطا در بارگذاری محصولات",
  ERROR_LOADING_PRODUCT: "خطا در بارگذاری محصول",
  ERROR_LOADING_DATA: "خطا در بارگذاری اطلاعات",
  ERROR_NETWORK: "خطا در اتصال به سرور",
  SCODE_CREEP: "این قابلیت خارج از ظرفیت این برنامه است",
};
