export const CONTENT = {
  BACK: "بازگشت",
  PRODUCT_DESCRIPTION: "جزئیات محصول",
  CART: "سبد خرید",
  ADD_TO_CART: "افزودن به سبد خرید",
  PRODUCT_NOT_FOUND: "محصول یافت نشد",
  PRODUCT_NOT_FOUND_DESCRIPTION: "متأسفانه محصول مورد نظر یافت نشد",
  CART_EMPTY: "سبد خرید شما خالی است",
  CART_EMPTY_DESCRIPTION: "محصولات خود را به سبد خرید اضافه کنید",
  SUBTOTAL: "جمع:",
  TOTAL: "مجموع کل:",
  CHECKOUT: "پرداخت",
  CLEAR_CART: "پاک کردن",
  CLOSE: "بستن",
  DECREASE_QUANTITY: "کاهش تعداد",
  INCREASE_QUANTITY: "افزایش تعداد",
  VIEW: "مشاهده",
  NO_PRODUCTS_FOUND: "محصولی یافت نشد",
  NO_PRODUCTS_DESCRIPTION: "در حال حاضر محصولی در دسترس نیست",
  PRICE: "قیمت:",
  UNIT_PRICE: "قیمت واحد:",
  APP_TITLE: "اسنپ شاپ",
  APP_DESCRIPTION: "فروشگاه اینترنتی اسنپ شاپ",
};
